version: '3.3'
services:
  nginx:
    restart: unless-stopped
    container_name: dev_nginx
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./backend/algoser/django_static:/app/backend/algoser/server/django_static
      - ./backend/algoser/media:/app/backend/algoser/server/media
      - ./nginx/development:/etc/nginx/conf.d

volumes:
  static_volume: {}