# Generated by Django 4.0 on 2024-04-08 14:40

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='photo',
            field=models.FileField(default=1, upload_to=posts.models.user_directory_path, verbose_name='Изображение поста'),
            preserve_default=False,
        ),
    ]
